---
- name: Install and Configure HTTPD
  hosts: all
  become: true
  tasks:
    - name: Install HTTPD (Apache)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable HTTPD Service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Open HTTP Port in Firewall
      ansible.builtin.firewalld:
        service: http
        permanent: true
        state: enabled
      notify: Restart Firewalld

  handlers:
    - name: Restart Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: restarted

