---
- name: Set Welcome Message
  hosts: all
  become: yes
  tasks:
    - name: Update /etc/motd
      copy:
        content: |
          **********************************************************
          *   Welcome to {{ ansible_hostname }} from Ahmed Khamis                 *
          *   Managed by Ansible!                                   *
          ***********************************************************
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'


